/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-courses` | `/my-courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/course/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/documents/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } } | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/quiz/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-courses` | `/my-courses`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/course/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/documents/[courseId]`, params: Router.UnknownOutputParams & { courseId: string; } } | { pathname: `/lesson/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/quiz/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/../hooks/use-color-scheme${`?${string}` | `#${string}` | ''}` | `/../components/haptic-tab${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-courses${`?${string}` | `#${string}` | ''}` | `/my-courses${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/use-color-scheme`; params?: Router.UnknownInputParams; } | { pathname: `/../components/haptic-tab`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-courses` | `/my-courses`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/course/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/documents/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/lesson/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/quiz/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/course/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/documents/[courseId]`, params: Router.UnknownInputParams & { courseId: string | number; } } | { pathname: `/lesson/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/quiz/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
